# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dq8fbyPQHyuu0IjJZEw3lKST2e-LQTpR
"""

class Pessoa():
  def __init__(self,nome:str):
    self.nome = nome


p1 = Pessoa("Max")
p1.nome = "João"